[package]
name = "server"
version = "0.1.0"
authors = ["Vikas Sahu <vikassahu2904@gmail.com>"]

[dependencies]
iron = "*"
router = "*"
persistent = "*"
serde = "*"
serde_derive = "*"
serde_json = "*"
hyper = "*"
uuid = { version = "0.7", features = ["v4"] }
ws = "*"